### ISSUE TITLE
rrdtool no longer ships python modules

### ISSUE THREAD

**Issue by sjorge** [omniosorg/omnios-extra#1033]
Look like the latest rrdtool no longer ships the python module in: /opt/ooce/rrdtool/lib/python3.<ver>/site-packages, I was using this in a few locations.

Was this removed intentionally?

**Comment by hadfl** [comment]
Thanks for the bug report. This looks like a regression due to the move to python 3.10 and `configure` in the rrdtool source bundle created with an older autoconf version.

autoconf used to extract the python version like this:
```
am_cv_python_version=`$PYTHON -c "import sys; sys.stdout.write(sys.version[:3])"`
```
which truncates at 3 characters, so we end up with 3.1 instead of 3.10
