### ISSUE TITLE
README.md functions.sh vs build.sh

### ISSUE THREAD

**Issue by r7st** [omniosorg/omnios-extra#1132]
The README.md file describes using:
`. ../../lib/functions.sh`
in package build.sh scripts, but I was unable to successfully build a new package without:
`. ../../lib/build.sh`
Looking at other packages, it seems all of them use `build.sh`, and not `functions.sh` directly.

If this is the case, should the documentation be updated to reflect this?

**Comment by citrus-it** [comment]
Thanks, I've opened a PR to correct the documentation.
