### ISSUE TITLE
gdb has scheme timestamp trouble

### ISSUE THREAD

**Issue by richlowe** [omniosorg/omnios-extra#1336]
I installed `pkg://extra.omnios/ooce/developer/gdb@13.2-151047.0:20230714T085149Z`

And ran `gdb <somebinary>` to look at something, it spat out many warnings about scheme things, that I suspect all really root cause to the first couple, which look like the problem many things (especially python) have where source/compiled timestamps must be preserved

```
;;; note: source file /opt/ooce/guile/share/guile/2.0/ice-9/eval.scm
;;;       newer than compiled /opt/ooce/lib/amd64/guile/2.0/ccache/ice-9/eval.go
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /opt/ooce/guile/share/guile/2.0/oop/goops.scm
;;; compiling /opt/ooce/guile/share/guile/2.0/system/base/compile.scm
;;; it seems /opt/ooce/guile/share/guile/2.0/system/base/compile.scm
;;; is part of the compiler; skipping auto-compilation
;;; compiling /opt/ooce/guile/share/guile/2.0/system/base/syntax.scm
;;; it seems /opt/ooce/guile/share/guile/2.0/system/base/syntax.scm
;;; is part of the compiler; skipping auto-compilation
...
;;; compiling /opt/ooce/guile/share/guile/2.0/ice-9/pretty-print.scm
;;; WARNING: compilation of /opt/ooce/guile/share/guile/2.0/ice-9/pretty-print.scm failed:
;;; ERROR: no such language scheme

;;; compiling /opt/ooce/guile/share/guile/2.0/language/tree-il/spec.scm
;;; WARNING: compilation of /opt/ooce/guile/share/guile/2.0/language/tree-il/spec.scm failed:
;;; ERROR: no such language tree-il
```

And many more along similar lines.  I suspect the important thing is to preserve timestamps on *.scm, hopefully the other errors all come down to that basic issue too.

**Comment by hadfl** [comment]
The issue you are seeing was due to an incorrect pattern, so .scm timestamps were not preserved. The following commit should have fixed it: https://github.com/omniosorg/omnios-extra/commit/c7345b17c768c8fb59c2efe02217510c2621ddb5

Can you confirm that this is ok now?

**Comment by richlowe** [comment]
It seems to be fine now, thanks!
