### ISSUE TITLE
FreeRADIUS 3.2.5 package broken

### ISSUE THREAD

**Issue by sjorge** [omniosorg/omnios-extra#1494]
The version bump in https://github.com/omniosorg/omnios-extra/pull/1490/commits/d949ef06b16e6323c2cd1a4fae2e3cecfcd138a0 seems to have broken FreeRADIUS on omnios-bloody.

```
[ Jul 28 16:11:41 Executing start method ("/opt/ooce/freeradius/sbin/radiusd -d /etc/opt/ooce/freeradius_acheron"). ]
[16:12:42]
ld.so.1: radiusd: fatal: relocation error: file /opt/ooce/freeradius/lib/amd64/libfreeradius-server.so: symbol _talloc_zero: referenced symbol not found
```

There seem to be some talloc changes in that commit so it seems related.

@hadfl ping

**Comment by hadfl** [comment]
This looks like a fallout from linking talloc statically. We should revert it to use the shared talloc library.
