### ISSUE TITLE
ooce/application/php-80/imagick

### ISSUE THREAD

**Issue by beiDei8z** [omniosorg/omnios-extra#750]
Please provide:
ooce/application/php-80/imagick

```
$ pkg search -r -H -o pkg.name imagick.so
ooce/application/php-73/imagick
ooce/application/php-74/imagick
```
Thank you.

**Comment by citrus-it** [comment]
As soon as there's a release of `php-imagick` that supports PHP 8, the package will be added to omnios-extra.

You can track progress at https://github.com/Imagick/imagick/issues/

**Comment by beiDei8z** [comment]
How anyone can release software (php 8) that "does not work" is beyond me.

**Comment by citrus-it** [comment]
php-imagick is a third-party extension which has not been updated for PHP 8 yet.

**Comment by beiDei8z** [comment]
[https://www.php.net/manual/en/intro.imagick.php](https://www.php.net/manual/en/intro.imagick.php)

"Imagick is a **native** php extension to create and modify images using the ImageMagick API."

**Comment by citrus-it** [comment]
https://www.php.net/manual/en/imagick.installation.php

> This PECL extension is not bundled with PHP.

I don't think those are incompatible statements. At the current time, the latest release of the `imagick` cannot be built for PHP 8.
See https://pecl.php.net/package/imagick for information about the extension.

The most recently created bug against this is at https://bugs.php.net/bug.php?id=80474 and includes:

![image](https://user-images.githubusercontent.com/29426693/102237820-f6dfd400-3eec-11eb-94b9-17279b85100e.png)
