### ISSUE TITLE
php configured path does not point to php.ini

### ISSUE THREAD

**Issue by beiDei8z** [omniosorg/omnios-extra#751]
#  summary
php configured path does not point to php.ini
# detail
configure parameter "--with-config-file-path" is a directory not the file.

```
./configure
...
  --with-config-file-path=PATH
                          Set the path in which to look for php.ini
                          [PREFIX/lib]
```

`'./configure' '--prefix=/opt/ooce/php-8.0' '--sysconfdir=/etc/opt/ooce/php-8.0' '--localstatedir=/var/opt/ooce/php' '--with-config-file-path=/etc/opt/ooce/php-8.0/php.ini' '--disable-libgcc' '--with-iconv' '--enable-dtrace' '--enable-ftp' '--enable-mbstring' '--enable-calendar' '--enable-dba' '--enable-soap' '--with-gettext' '--enable-pcntl' '--with-openssl' '--with-gmp' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-zlib=/usr' '--with-zlib-dir=/usr' '--with-bz2=/usr' '--with-curl' '--enable-gd' '--with-external-gd' '--enable-sockets' '--enable-bcmath' '--enable-exif' '--with-zip' '--with-db4=/opt/ooce' '--with-lmdb=/opt/ooce' '--with-ldap=/opt/ooce' '--with-pgsql=/opt/ooce/pgsql-12' '--with-pdo-pgsql=/opt/ooce/pgsql-12' '--enable-fpm' '--with-fpm-user=php' '--with-fpm-group=php' 'PKG_CONFIG_PATH=/opt/ooce/lib/amd64/pkgconfig' 'CFLAGS= -O2 -fno-aggressive-loop-optimizations -m64' 'CXXFLAGS= -O2 -fno-aggressive-loop-optimizations -m64' `

```
# /opt/ooce/php-8.0/bin/php --ini
Configuration File (php.ini) Path: /etc/opt/ooce/php-8.0/php.ini
Loaded Configuration File:         (none)
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

# /opt/ooce/php-8.0/bin/php --ini -c /etc/opt/ooce/php-8.0/php.ini
Configuration File (php.ini) Path: /etc/opt/ooce/php-8.0/php.ini
Loaded Configuration File:         /etc/opt/ooce/php-8.0/php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

# mkdir /etc/opt/ooce/php-8.0/anything
# mv /etc/opt/ooce/php-8.0/php.ini /etc/opt/ooce/php-8.0/anything
# mv /etc/opt/ooce/php-8.0/anything /etc/opt/ooce/php-8.0/php.ini
# /opt/ooce/php-8.0/bin/php --ini
Configuration File (php.ini) Path: /etc/opt/ooce/php-8.0/php.ini
Loaded Configuration File:         /etc/opt/ooce/php-8.0/php.ini/php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)


```
php-fpm works because it uses a package configuration value:

```
# svccfg -s php80:default listprop config/file
config/file  astring  /etc/opt/ooce/php-8.0/php.ini

```
# packages affected
Tested:
```
# pkg list php-74 php-80
NAME (PUBLISHER)                                  VERSION                    IFO
ooce/application/php-74 (extra.omnios)            7.4.13-151030.0            i--
ooce/application/php-80 (extra.omnios)            8.0.0-151030.0             i--
```
and probably ooce/application/php-73, not tested.

# desired result
(three issues, #749 #750 #751)
`# echo '<?php echo @extension_loaded("imagick") ? "yes\n" : "no\n" ?>' | /opt/ooce/php-8.0/bin/php`
...to say "yes".
Thank you.
James.

**Comment by citrus-it** [comment]
Thanks for the report. I've opened a PR to fix this and updated packages should be available shortly.

**Comment by beiDei8z** [comment]
Possibly additional change:
/var/opt/ooce/php/log/php-fpm.log
is shared by the different PHP versions. Running 2 PHPs concurrently works and both write to the same file.

--localstatedir=/var/opt/ooce/php
might be better as
--localstatedir=/var/opt/ooce/php-8.0
just as --sysconfdir includes a version
...whatever works and does not trick the user.  What else might go in /var/opt/ooce/php?

**Comment by citrus-it** [comment]
Good point, thanks. I've updated the pull request with this too.
