### ISSUE TITLE
Possibly add haproxy to tools

### ISSUE THREAD

**Issue by lispstudent** [omniosorg/omnios-extra#799]
[Haproxy](http://cbonte.github.io/haproxy-dconv/2.3/intro.html#3.3) is a very useful tool, dispatching ([sub-layer 4 up to layer-7](https://www.haproxy.com/blog/layer-4-and-layer-7-proxy-mode/)) traffic to zones.

One could use haproxy installed in a pkgsrc zone, but, being so nice for many use cases and quite established, would you consider adding it to omnios-extra `tools`?

I would not mind to try and send a PR, but I would need quite a bit of hand holding, as I am not practical with compiling.

Apologies if this is the wrong place to ask (in such case, where is the right place?). Please close as needed.

**Comment by lispstudent** [comment]
Perhaps of some use, haproxy at [oi-userland](https://github.com/OpenIndiana/oi-userland/tree/50eff705f74b66bd1062346a883a1a06c988db08/components/web/haproxy).

**Comment by hadfl** [comment]
`haproxy` certainly looks useful and I don't think anything speaks against adding it to the `omnios-extra` publisher. I'll have a look and let you know once we have a package ready for you to test.

**Comment by lispstudent** [comment]
Wonderful, much obliged.

**Comment by hadfl** [comment]
--> https://github.com/omniosorg/omnios-extra/pull/801

if you let me know which OmniOS release you are using I can build a signed package for you to test.

**Comment by lispstudent** [comment]
```
uname -a
SunOS omnios 5.11 omnios-r151036-a13510b579 i86pc i386 i86pc
```

Thank you.

**Comment by hadfl** [comment]
`pkg apply-hot-fix https://hf.omniosce.org/r151036/haproxy_r36.p5p haproxy`

**Comment by lispstudent** [comment]
Thanks. Installation went fine. I will now test with my haproxy config.

I'll be travelling in an hour, will report back Monday.

**Comment by lispstudent** [comment]
It is great! I checked with a simple configuration, everything looks good, including stats.

<img width="874" alt="omnisos-haproxy" src="https://user-images.githubusercontent.com/59874114/107852198-bb3f8880-6e0f-11eb-9848-731112b15eb2.png">

As far as I'm concerned this could be closed.

Thank you, also to show how to create a package (now I need to learn how to build the corresponding signed package.)


---

Note: For other testers, this is the simple (and contrived) config:

```
$ cat /etc/opt/ooce/haproxy/haproxy.cfg
global
  daemon
  log 127.0.0.1 local0
  log 127.0.0.1 local1 notice
  maxconn 4096
  tune.ssl.default-dh-param 2048

defaults
  log               global
  retries           3
  maxconn           2000
  timeout connect   5s
  timeout client    50s
  timeout server    50s

frontend www-stats
  bind 0.0.0.0:8080
  mode http
  stats enable
  stats uri /
  stats realm Haproxy\ Statistics
  stats auth user:password

frontend microservice_1
  bind *:80
  mode http
  http-response set-header X-Frame-Options DENY
  use_backend octo

frontend microservice_2
  bind *:81
  mode http
  use_backend irc


backend irc
  mode http
  server irc1 192.168.178.50:80 check


backend octo
  mode http
  server octo1 192.168.178.51:81 check
```

**Comment by hadfl** [comment]
Thank you very much for testing and providing feedback!

Usually when adding a new package, one would use the OmniOS `bloody` release where packages being signed is not enforced by default and therefore possible to just install them from the local repository w/o taking care of signing it (you can easily run a bloody vm using bhyve on your r36 machine).

If you want to understand package signing, have a look at at the `pkgsign(1)` man page, the CA certificates for pkg which it trusts derived certs from are located under `/etc/ssl/pkg` so you could drop-in your own CA there (and sign packages with your own key/cert)

we use our own [pkgmgr](https://github.com/omniosorg/pkgmgr) for package signing/publishing/exporting.

**Comment by lispstudent** [comment]
Thank you for the details. I will try installing `bloody` vm, and then learn package building first. Thank you, truly appreciated.

**Comment by hadfl** [comment]
You're welcome. Don't hesitate to reach out if questions arise https://omniosce.org/about/contact.html
