### ISSUE TITLE
Enable additional codecs for ffmpeg build

### ISSUE THREAD

**Issue by cbinner** [omniosorg/omnios-extra#817]
It would be nice if ooce/multimedia/ffmpeg could support encoding additional codecs (h264, maybe h265) for some basic video transcoding.
This would require packaging the external libx264/libx265 libraries.
ffmpeg build options for x264 are `--enable-libx264 --enable-gpl`

Joyent's pkgsrc builds libx264 with `--disable-asm` since it broke for illumos after this commit: https://code.videolan.org/videolan/x264/-/commit/a615f027ed172e2dd5380e736d487aa858a0c4ff
Disabling the custom assembler roughly halves encoding speed so it would be nice to get it working again.
Openindiana ships an older libx264.

The commit linked above doesn’t explicitly alter the assembler code but rather changes the build system resulting in this error:
`ld: fatal: relocations remain against allocatable but non-writable sections`

OpenIndiana has an additional patch in order to avoid using `/usr/ucb/install`:
https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/encumbered/x264/patches/01-avoid-ucb-install.patch

Many places still pull the code from this discontinued mirror: http://download.videolan.org/pub/videolan/x264/snapshots/

The better way seems to picking CI-blessed commits from here: https://code.videolan.org/videolan/x264/-/commits/stable (maybe following https://github.com/archlinux/svntogit-packages/commits/packages/x264/trunk/PKGBUILD )

**Comment by hadfl** [comment]
hi @cbinner, we already have a PR in place since earlier tonight. please have a look:
https://github.com/omniosorg/omnios-extra/pull/816

 once merged the updated packages are soon available from the `extra.omnios` repository.
