### ISSUE TITLE
Possibly add fail2ban to tools

### ISSUE THREAD

**Issue by lispstudent** [omniosorg/omnios-extra#918]
[Fail2ban](https://github.com/fail2ban/fail2ban) is used on many platforms to scans log files and bans IPs that show the malicious signs by updating firewall rules to reject the IP addresses for a specified amount of time.

It installs fine manually, but, being so nice for many use cases and quite established, would you consider adding it to omnios-extra tools?

I could not see an OpenIndiana package to use as reference, but I know it is available as [pkgsrc package](https://github.com/joyent/pkgsrc/tree/trunk/security/fail2ban).

PS: I am still struggling in understanding how to install and operate a zone to build packages, so I can try submitting PRs. Is there somewhere a tutorial? It would so nice to have something like the very useful zadm tutorials.

**Comment by sjorge** [comment]
It's documented in the repo's README.md https://github.com/omniosorg/omnios-extra#requirements

If anything is unclear it worth filing an issue to get it clarified.

**Comment by lispstudent** [comment]
> If anything is unclear it worth filing an issue to get it clarified.

Thanks @sjorge, I am an absolute beginner. I'll try and in case file a ticket.

**Comment by lispstudent** [comment]
I am working on this, going a bit slow since exams are coming. Please feel free to close it, and I will reopen it at later time.

**Comment by lispstudent** [comment]
My Prof mentioned it is not good manners to keep a ticket open, waiting for one's own time, especially on a repository so tidy and well kept as this one. It is imposing one's disorderly workflow over a deeper, more structured (and higher, he added) standard.

With your permission, I am closing this and #919. I will reopen them if/when I will be ready to submit a proper MR. My apologies, and thank you for your patience.
